- composer.json
- config/install/core.entity_form_display.child_para.soe_text_image_cta.default.yml
- config/install/core.entity_form_display.paragraph.soe_text_image_cta.default.yml
- config/install/core.entity_view_display.child_para.soe_text_image_cta.default.yml
- config/install/core.entity_view_display.paragraph.soe_text_image_cta.default.yml
- config/install/ds.field.soe_cta_link.yml
- config/install/eck.eck_entity_type.child_para.yml
- config/install/eck.eck_type.child_para.soe_text_image_cta.yml
- config/install/field.field.child_para.soe_text_image_cta.soe_text_cta_image.yml
- config/install/field.field.child_para.soe_text_image_cta.soe_text_cta_link.yml
- config/install/field.field.paragraph.soe_text_image_cta.soe_text_cta_body.yml
- config/install/field.field.paragraph.soe_text_image_cta.soe_text_cta_cards.yml
- config/install/field.field.paragraph.soe_text_image_cta.soe_text_cta_heading.yml
- config/install/field.storage.child_para.soe_text_cta_image.yml
- config/install/field.storage.child_para.soe_text_cta_link.yml
- config/install/field.storage.paragraph.soe_text_cta_body.yml
- config/install/field.storage.paragraph.soe_text_cta_cards.yml
- config/install/field.storage.paragraph.soe_text_cta_heading.yml
- config/install/paragraphs.paragraphs_type.soe_text_image_cta.yml
- css/soe_profile.text_cta_cards.css
- soe_profile.info.yml
- soe_profile.libraries.yml
- soe_profile.profile
- Paragraph for text with card list.
- at some point
- low
1. in the lelandd8 stack with branch [`soe-prep`](https://github.com/SU-SWS/acsf-lelandd8/pull/1): `composer require su-soe/soe_profile:dev-JACK-216-text-cta-list`
1. run a full install
1. create a basic page and add a "Text with Image Link"
1. populate it with some content. add as many cards as you'd like
1. review the output is kinda like the [mockups](https://www.figma.com/file/Uo5IFFsNTt0N79rXGvNvoz/SOE-Paragraphs-Components?node-id=50%3A0)
> JACK216 Text Image CTA paragraph

- config/install/views.view.content.yml
- soe_profile.info.yml
- syncing vbo 3.6 with config
- When does this need to be merged by?
- Critical
1. checkout this branch
2. compoaser update --prefer-source
3. from stack root run a blt drupal:install and verify no errors when installing or viewing /admin/content
- lelandd8 product
- https://stanfordits.atlassian.net/browse/D8CORE-1670
> updated config for vbo and views unpublished

- composer.json
- config/sync/core.extension.yml
- config/sync/editor.editor.stanford_html.yml
- soe_profile.info.yml
- Updating D8CORE-1698 with changes in stanford profile
preferrably before:
- https://github.com/SU-SOE/soe_profile/pull/8
- https://github.com/SU-SWS/acsf-lelandd8/pull/10
- we need it
1. Test as if you were testing https://github.com/SU-SWS/acsf-lelandd8/pull/10 but checkout this branch first and and from root of local stack: composer update --prefer-source
- lellandd8 stack and soe_profile
- https://stanfordits.atlassian.net/browse/D8CORE-1694
> updating to reflect changes in stanford profile

- composer.json
- stanford_ssp doesn't match what is in stanford_profile, so composer won't install
- asap
- we need it
1. use this branch in composer instead of D8CORE-1698
- lellandd8 stack
- D8CORE-1694: Review revise and test dynamic sync directory approach to stack and profile management
> matching stanford_ssp with stanford profile version

- composer.json
- Topic branch was merged
- asap
- critical
1. confirm stanford_news is set to base branch in composer.json
-lellandd8 builds
- @sherakama 
> moved news back to dev

- config/sync/core.extension.yml
- config/sync/metatag.metatag_defaults.node.yml
- config/sync/metatag.metatag_defaults.page_variant__stanford_news_list-layout_builder-0.yml
- config/sync/metatag.metatag_defaults.taxonomy_term.yml
- config/sync/metatag.settings.yml
- soe_profile.info.yml
- Adding metatag data for news to profile
- Before https://github.com/SU-SOE/soe_profile/pull/12 gets merged
- we need it
1. verify metatag setting match basic page
- lellandd8 stack
- https://stanfordits.atlassian.net/browse/D8CORE-1896
> saved metatag data for news node

- config/sync/metatag.metatag_defaults.node.yml
- Reverts the changes to the default node setting.
- Please pick up this branch and add a separate config for news node types
- May 1st
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
- Anyone who should be notified? (`@mention` them here)
> Revert changes to default node setting

- .circleci/config.yml
- composer.json
- src/Plugin/InstallTask/SiteSettings.php
- tests/behat/features/Users/Roles.feature
- tests/src/Kernel/Plugin/InstallTask/RouteRebuilderTest.php
- tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php
- tests/src/Kernel/Plugin/InstallTask/UsersTest.php
- tests/src/Kernel/StanfordProfilePermissionsTest.php
- tests/src/Unit/EventSubscriber/EventSubscriberTest.php
- tests/src/Unit/Plugin/HelpSection/ProfileConnectSectionTest.php
- tests/src/Unit/Plugin/HelpSection/ProfileHelpSectionTest.php
- tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
- Ensure that CircleCI integration is working and the initial tests for the `soe_profile` work as a stand-alone thing.
- ASAP
- Needed for the 1.2.0 release.
1.  The proof is in the pudding: https://app.circleci.com/pipelines/github/SU-SOE/soe_profile/24/workflows/9ad5648d-2dc6-4bc0-b58c-73bda5807cdd
- https://github.com/SU-SWS/acsf-lelandd8/pull/17
> Circleci Integration and testing

- .circleci/config.yml
- .github/auto-label.json
- .github/workflows/label.yml
- .github/workflows/tag_commits_to_master.yml
- config/sync/system.site.yml
- soe_profile.services.yml
- src/Config/ConfigOverrides.php
- tests/behat/features/SystemSiteConfig.feature
- tests/codeception/acceptance/HomePageCest.php
- tests/src/Unit/Config/ConfigOverridesTest.php
- Moved some testing things from `stanford_profile` to here, in order for the stack repo to pass acceptance tests.
- While I was at it,  I put in the stuff for autotagging on the master branch, as well as back-to-dev in circle and github pr autolabeler.
- ASAP
Passes circleci on its own.  The real test is if it passes with the stack checks.
https://github.com/SU-SWS/acsf-lelandd8/pull/17
> Home url test

- composer.json
- soe_profile.info.yml
> back to dev

- config/sync/auto_entitylabel.settings.paragraph.stanford_stories.yml
- config/sync/core.entity_form_display.paragraph.stanford_stories.default.yml
- config/sync/core.entity_view_display.paragraph.stanford_stories.default.yml
- config/sync/field.field.paragraph.stanford_stories.stanford_stories_border.yml
- config/sync/field.field.paragraph.stanford_stories.stanford_stories_cta_link.yml
- config/sync/field.field.paragraph.stanford_stories.stanford_stories_name.yml
- config/sync/field.field.paragraph.stanford_stories.stanford_stories_node_link.yml
- config/sync/field.field.paragraph.stanford_stories.stanford_stories_photo.yml
- config/sync/field.field.paragraph.stanford_stories.stanford_stories_quote.yml
- config/sync/field.field.paragraph.stanford_stories.stanford_stories_title.yml
- config/sync/field.storage.paragraph.stanford_stories_border.yml
- config/sync/field.storage.paragraph.stanford_stories_cta_link.yml
- config/sync/field.storage.paragraph.stanford_stories_name.yml
- config/sync/field.storage.paragraph.stanford_stories_node_link.yml
- config/sync/field.storage.paragraph.stanford_stories_photo.yml
- config/sync/field.storage.paragraph.stanford_stories_quote.yml
- config/sync/field.storage.paragraph.stanford_stories_title.yml
- config/sync/paragraphs.paragraphs_type.stanford_stories.yml
- config changes to rename the photo border field in soe_paragraphs/stanford_stories
> D8core 000 field rename

- composer.json
- tests/codeception/acceptance/Paragraphs/StanfordCTAListCest.php
- tests/codeception/acceptance/Paragraphs/StanfordImageCTACest.php
- tests/codeception/acceptance/Paragraphs/StanfordStoriesCest.php
- Basic tests for SOE paragraphs.
- 7/9/2020
- not critical, except tests are nice.
1. observe the tests complete successfully in Codeception.
> D8CORE-2273: added tests for cta list and image cta

- config/sync/core.entity_view_display.node.stanford_event_series.default.yml
- config/sync/page_manager.page_variant.people-layout_builder-0.yml
- config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
- config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
- config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
- People layout changes
- Wednesday
- Medium
1. Do pull this branch and the matching one on SOE Theme
2. import configs 
3. verify there are changed headers for People.
- SOE Subtheme
- D8CORE-2252
- Matching PR on Theme.
- https://github.com/SU-SOE/soe_profile/pull/54
> D8CORE-2252: Person config changes.

- config/sync/core.entity_view_display.node.stanford_event_series.default.yml
- config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
- config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
- Sub theme work for the SOE News module.
- soon
- Med
1. Pull in this branch
2. Pull in SOE profile branch
3. Update configs
4. Recompile
5. Check on the pages that they match the designs.
- SOE Subtheming
/news - filtered and not
- D8CORE-1579
- https://github.com/SU-SOE/soe_profile/pull/50
- https://github.com/SU-SOE/soe_basic/pull/12
- Theming for the  News section
- @imonroe 
> D8CORE-1579: fixing up the circleci errors

- composer.json
- config/sync/config_ignore.settings.yml
- config/sync/config_pages.type.stanford_basic_site_settings.yml
- config/sync/config_pages.type.stanford_events_importer.yml
- config/sync/config_pages.type.stanford_local_footer.yml
- config/sync/config_pages.type.stanford_person_importer.yml
- config/sync/config_pages.type.stanford_saml.yml
- config/sync/filter.format.stanford_html.yml
- config/sync/stanford_basic.settings.yml
- config/sync/views.view.content.yml
- soe_profile.info.yml
- src/Config/ConfigOverrides.php
- src/Plugin/HelpSection/ProfileHelpSection.php
- src/Plugin/HelpSection/ProfileResourceSection.php
- tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
- tests/src/Unit/Config/ConfigOverridesTest.php
- tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
- Diff comparison of 8.1.15 of stanford_profile to latest in D8CORE-2453
- Today(ish)
> D8CORE-2453: Missing changes from diff.

- composer.json
- Updates patch
- Soonish as builds are breaking.
- Medium
1. Review code changes
2. Review passing tests
3. For bonus points do a full cardinalsites build with this branch.
> DEVOPS-000: Update paragraphs lang patch

- tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
- tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
> D8CORE-000: Lockup tests and shuffle dance

- tests/codeception/functional/Users/RolesCest.php
- I built out this test, so we might as well use it. It verifies the user can't bulk delete the home page.
- 10/5 i guess
- low
1. View the tests.
> D8CORE-1200 Delete protection of home page

- config/sync/core.entity_form_display.node.stanford_page.default.yml
- Only allow 1 CTA list or Story per row
- 9/25
- Medium
1. Pull in this change
2. Verify that only one CTA List or Story can be added per row.
3. Verify that the rows that had multiple CTA list or Stories stayed the same.
- SOE, Stories and CTA List
- D8CORE-2773
> D8CORE-2773: change the number of items in a row 

- config/sync/extlink.settings.yml
- tests/codeception/functional/Contrib/ExtLinkCest.php
- Disable external link module settings
- asap
- critical
> Disabled external links

- config/sync/extlink.settings.yml
- Adding the External Links for SOE
- 11/15/20 - needs to be in the 1.5.1
- High
1. Pull in this change.
2. Pull in the the SOE theming changes.
3. Refresh everything. 
4. Verify there are not duplicate arrow and the colors of the links match.
5.  A fair amount of testing will need to occur on the SOE sites.
- 2670, 2671, 2672, 2673 
- 2674 - needs work in the module 
- https://github.com/SU-SOE/soe_basic/pull/46
- @rmundstock 
> D8CORE-2670: configs for the ext link

- composer.json
- config/sync/core.entity_form_display.media.google_form.default.yml
- config/sync/core.entity_form_display.media.google_form.media_library.yml
- config/sync/core.entity_view_display.media.google_form.default.yml
- config/sync/core.entity_view_display.media.google_form.media_library.yml
- config/sync/field.field.media.google_form.field_media_google_form_hgt.yml
- config/sync/field.storage.media.field_media_google_form_hgt.yml
- config/sync/media.type.google_form.yml
- tests/codeception/acceptance/Media/MediaCest.php
- tests/codeception/functional/Paragraphs/WYSIWYGCest.php
- tests/src/Kernel/Plugin/InstallTask/RouteRebuilderTest.php
- tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php
- tests/src/Kernel/Plugin/InstallTask/UsersTest.php
- tests/src/Kernel/StanfordProfilePermissionsTest.php
- tests/src/Unit/Config/ConfigOverridesTest.php
- tests/src/Unit/EventSubscriber/EventSubscriberTest.php
- syncs configs, tests, etc. from stanford_profile to soe_profile
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
- Anyone who should be notified? (`@mention` them here)
> D8CORE-3070: updated configs and tests

- config/sync/block.block.stanford_basic_pagetitle.yml
- config/sync/core.entity_view_display.citation.su_thesis.default.yml
- config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
- config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
- config/sync/core.extension.yml
- config/sync/field.field.citation.su_thesis.su_publisher.yml
- config/sync/field.field.citation.su_thesis.su_year.yml
- config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
- config/sync/system.menu.stanford-publication-topics.yml
- config/sync/taxonomy_menu.taxonomy_menu.publication_topics.yml
- config/sync/views.view.publication_terms.yml
- config/sync/views.view.stanford_events.yml
- config/sync/views.view.stanford_news.yml
- config/sync/views.view.stanford_person.yml
- config/sync/views.view.stanford_publications.yml
- content/node/ce9cb7ca-6c59-4eea-9934-0a33057a7ff2.yml
- content/paragraph/9939d5e0-a261-4f99-b08a-9ba5b43908c1.yml
- content/paragraph_row/e9158340-cb5c-494e-9c66-a959208fe4a8.yml
- tests/codeception/acceptance/Content/PublicationsCest.php
- tests/codeception/functional/Contrib/RedirectImportCest.php
- (Edit the above to reflect status)
- TL;DR - what's this PR for?
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
- Anyone who should be notified? (`@mention` them here)
> Updates from stanford_profile

- config/sync/block.block.soe_basic_pagetitle.yml
- config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
- Adding classes and removing the title on the publication pages.
- 3/3
- high
1. Pull in this change.
2. Pull in the SOE change: https://github.com/SU-SOE/soe_basic/pull/66
3. Refresh everything
4. Make some publications content.
5. Verify that publications has the gradient header on the /publications and the /publications/term name
- SOE
- D8CORE-3577
- D8CORE-3247
- D8CORE-3580
- https://github.com/SU-SOE/soe_basic/pull/66
> D8CORE-3247: updates for the background header colors

- .circleci/config.yml
- config/sync/views.view.stanford_news.yml
- tests/codeception/acceptance/Content/NewsCest.php
- tests/codeception/acceptance/Users/IntranetCest.php
- tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
- D8CORE-4090 D8CORE-2888 D8CORE-4126: accessbility changes to the news modules. (#425)
- Corrected acceptance tests with the latest dependency updates (#427)
- (Edit the above to reflect status)
- TL;DR - what's this PR for?
- When does this need to be merged by?
- How critical is this PR?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
- Anyone who should be notified? (`@mention` them here)
> Stanford Profile updates 2021-06-09

- config/sync/core.entity_view_display.taxonomy_term.stanford_event_types.default.yml
- config/sync/core.entity_view_display.taxonomy_term.stanford_news_topics.default.yml
- config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
- config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
- tests/codeception/functional/Contrib/ExtLinkCest.php
- Fixing the headers to the list pages: Events, Past Events, publications, News, People.
- Fixing the filtered pages for the above list.
- ASAP
- High
- Only the SOE 
- High
1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to to the pages listed above and verify the gradient is on all the header for the list and the filtered. 
- Is there a config:export in this PR that changes the config sync directory? YES a
- [D8CORE-5826](https://stanfordits.atlassian.net/browse/D8CORE-5826)
- https://github.com/SU-SOE/soe_profile/pull/251
- https://github.com/SU-SOE/soe_basic/pull/97
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test …
> D8CORE-5826: updating the header background images.

- .gitpod.yml
- README.md
- Setup gitpod configurations.
- :shrug: 
- low
1. follow the instructions in the Readme file.
> D8CORE-4348 Setup Gitpod

- composer.json
- config/sync/config_split.config_split.prod.yml
- (Edit the above to reflect status)
- TL;DR - what's this PR for?
- When does this need to be reviewed by?
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?
- How urgent is this? (Normal, High)
1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...
- Is there a config:export in this PR that changes the config sync directory?
- JIRA ticket(s)
- Other PRs
- Anyone who should be notified? …
> excise memcache
